# Build settings
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'CNAME', '.gitignore', '.gitattributes']


# Site settings
title: DevFest Nordeste 2015
email: contato@devfestne.com.br
description: "DevFest Nordeste é o maior evento de tecnologias Google do Nordeste"
baseurl: ""
url: "http://2015.devfestne.com.br"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-49492619-3"
googleAnalyticsSiteUrl: "devfestne.com.br"