# Build settings
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'CNAME', '.gitignore', '.gitattributes']


# Site settings
title: &default_title DevFest Nordeste 2015
author: "https://plus.google.com/+DevfestNEBR"
email: contato@devfestne.com.br
description: &default_description "DevFest Nordeste é o maior evento de tecnologias Google do Nordeste"
baseurl: ""
url: "http://2015.devfestne.com.br"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-49492619-3"
googleAnalyticsSiteUrl: "devfestne.com.br"

# Social sharing metadata
social_metadata:
  title: *default_title
  img: "/upload/blog_title_bg.jpg"
  description: *default_description
  twitter_account: "@DevFestNE"
  twitter_url: "http://www.twitter.com/DevFestNE"
  facebook_url: "http://facebook.com/devfestne"
  googleplus_url: "http://facebook.com/devfestne"
  linkedin_url: ""
  instagram_url: ""
  pinterest_url: ""

# Sections

# Home section
home:
  show: true
  title: "HOME"

# Intro section
intro:
  show: true
  title: "SOBRE"
  heading: "O que é um DevFest?"
  text: "GDG DevFests are large, community-run events that can offer speaker sessions across multiple product areas, all-day hack-a-thons, code labs, and more. In 2014, the official DevFest Season runs from September 15th through November 30th."

# Partners section
# Partner data in file _data/partners.yml
partners:
  show: true
  heading: "PATROCINADORES"

# Speakers section
# Speakers data in file _data/speakers.yml
speakers:
  show: true
  title: "PALESTRANTES"
  heading: "Nossos palestrantes"
  subheading: "Estamos bastante orgulhosos de tê-los conosco!"

# Call to action section
call:
  show: true
  title: "CALL"
  heading: "Está pronto para participar? Escolha como!"
  speak_text: "QUERO PALESTRAR"
  speak_url: "#"
  attend_text: "QUERO ASSISTIR"
  attend_url: "#"

# Agenda section
agenda:
  show: true
  title: "AGENDA"
  heading: "AGENDA"
  subheading: "Esse é o nosso planejamento. Mudanças na agenda poderão ser realizadas sem aviso prévio."
  read_more: "Veja mais"

# Venue section
venue:
  show: true
  title: "LOCAL"
  heading: "LOCAL"
  name: "Local"
  address: "Recife, Pernambuco - Brasil"
  info: "Here you can find some additional info about the venue."

# Team section
team:
  show: true
  title: "TIME"
  heading: "ORGANIZING COMITEE"
  subheading: "And also thanks to all our volunteers"